

services:
  PostgresDatabase:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - "./data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  PGAdmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "8080:80"